workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: <App Store Connect API key name>
    environment:
    scripts:
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: false
        expire_build_submitted_for_review: true
        beta_groups: 
          - QA
          - team
        
        submit_to_app_store: true
        cancel_previous_submissions: true
        
        release_type: SCHEDULED

        earliest_release_date: 2021-12-01T14:00:00+00:00 
        copyright: 2021 Nevercode Ltd
